// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCepRId81Y9gV2fOwem5kjIhBhxOoLLJD4',
    appId: '1:134598113086:web:REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: '134598113086',
    projectId: 'kisanbazaar-ca86d',
    storageBucket: 'kisanbazaar-ca86d.firebasestorage.app',
    authDomain: 'kisanbazaar-ca86d.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCepRId81Y9gV2fOwem5kjIhBhxOoLLJD4',
    appId: '1:134598113086:android:7aa8b6e6840692949e9e6f',
    messagingSenderId: '134598113086',
    projectId: 'kisanbazaar-ca86d',
    storageBucket: 'kisanbazaar-ca86d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCepRId81Y9gV2fOwem5kjIhBhxOoLLJD4',
    appId: '1:134598113086:ios:REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: '134598113086',
    projectId: 'kisanbazaar-ca86d',
    storageBucket: 'kisanbazaar-ca86d.firebasestorage.app',
    iosBundleId: 'com.mad.kisanbazaar',
  );
}
